version: '3.8'

services:
  hc_buckleyleverett:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/hc_buckleyleverett/results
    container_name: hc_buckleyleverett
    environment:
      - MPLBACKEND=Agg
